---
name: Run pylint

"on":
  push:
    branches:
      - master
  pull_request:

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Running ruff
        run: |
            python -m pip install --quiet --no-cache-dir --upgrade uv
            uv run ruff check $(basename $(pwd | sed -e 's/-/_/g'))
